### ISSUE TITLE
Wrong documentation for assign_attributes

### ISSUE THREAD

**Issue by NARKOZ** [aws/aws-sdk-ruby-record#105]
Documentation for `assign_attributes` says that it 

>deletes the item instance that matches the key values of this item 

https://github.com/aws/aws-sdk-ruby-record/blob/e88e2c04169bf531978a246264079365a7e624cb/lib/aws-record/record/item_operations.rb#L85-L86

**Comment by mullermp** [comment]
Thanks for reporting. I have fixed this.
https://github.com/aws/aws-sdk-ruby-record/commit/b48780dc085303a5f3b898fd3d40e61b9fb8226a
