### ISSUE TITLE
Support DynamoDB Encryption feature

### ISSUE THREAD

**Issue by kimyu92** [aws/aws-sdk-ruby-record#111]
Similar to dynamodb encryption provided for java and python,
https://github.com/aws/aws-dynamodb-encryption-java
https://github.com/aws/aws-dynamodb-encryption-python

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/EncryptionAtRest.html
Is there any plan to support this feature for ruby?

**Comment by mullermp** [comment]
Thanks for opening an issue. The SDK team does not own those two packages, but they look to be official. I don't know if there's a plan to support Ruby or not. I can put this feature request in front of them and find out.

**Comment by kimyu92** [comment]
Ideally, `aws-record` api would look something similar to unencrypted

```ruby
class MyModel
  include Aws::Record
  integer_attr :id, hash_key: true
  string_attr  :name, range_key: true, encrypted: true
  boolean_attr :active, database_attribute_name: "is_active_flag"
end
```

**Comment by alex-chew** [comment]
Hi kimyu92, thanks for reaching out. We don't have plans to support the DynamoDB Encryption Client in Ruby, but we'll take note of your feature request.

**Comment by mullermp** [comment]
Closing as we would not be owning client side encryption (@alex-chew's team has noted the feature request).
