### ISSUE TITLE
Batch get support

### ISSUE THREAD

**Issue by iamatypeofwalrus** [aws/aws-sdk-ruby-record#12]
I was diving into the code and I see methods for #scan and #query but not one for #batch_get_item. Is that something you'd like to see added at the ItemRecord level or should clients subclass and add methods as appropriate? In that case will methods like #_build_item_from_resp or  #_build_items_from_response become public?

I was thinking of a method like #find_items that would take in an array of primary key hashes and it would  handle unprocessed keys appropriately (I've worked low level with the Ruby SDK V1 so I'm not sure if either the V1 or V2 client handled unprocessed items appropriately).

Happy to send a PR if this isn't on a roadmap.

**Comment by awood45** [comment]
I do plan/want to add batched get support. I'd imagine this as a class method on the model class, which returns an ItemCollection. I don't think `_build_item*` methods should be made public, nor should they have to for this to work.

**Comment by awood45** [comment]
On further discussion, we're likely to solve this with a client-side abstraction. More on this down the road.

**Comment by awood45** [comment]
Going to implement this in the form of transactional get support.
