### ISSUE TITLE
Global Secondary Index Migration while inheriting table data

### ISSUE THREAD

**Issue by thomaswitt** [aws/aws-sdk-ruby-record#140]
When creating a GSI I have to define read_capacity_units, otherwise an error is raised. By default, global secondary indexes inherit the capacity settings of the base table. Global secondary indexes can have a different capacity mode only when the base table is in provisioned capacity mode.

This should bereflected, so it should be possible to just define `t.global_secondary_index(:gsi_name)` without supplying any request units.

E.g.
```
class BlogPost
  set_table_name "blogger"
  string_attr :hk, hash_key: true
  string_attr :rk, range_key: true
  string_attr :name
  string_attr :slug
  global_secondary_index(:slug_gsi,
                         hash_key: :hk,
                         range_key: :slug,
                         projection: { projection_type: 'KEYS_ONLY' })

    table_config = Aws::Record::TableConfig.define do |t|
      t.model_class(BlogPost)
      t.billing_mode 'PAY_PER_REQUEST'
      t.global_secondary_index(:slug_gsi)
    end
    table_config.migrate!
end
```

-

**Comment by jterapin** [comment]
Hi! Thank you for submitting the ticket. My apologizes for the delay and we will be taking a look.

**Comment by jterapin** [comment]
Updated [gem](https://rubygems.org/gems/aws-record/versions/2.13.2) has been released with the fix.
