### ISSUE TITLE
rake aws_record:migrate broken with two table configs on the same model

### ISSUE THREAD

**Issue by thomaswitt** [aws/aws-sdk-ruby-record#143]
When creating two global secondary indexes for the same model, this leads to the following error message:
```bash
$ rake aws_record:migrate
running db/table_config/gsi_user_login.rb
running db/table_config/user_email_gsi.rb
Aws::DynamoDB::Errors::LimitExceededException: Subscriber limit exceeded: Only 1 online index can be created or deleted simultaneously per table (Aws::DynamoDB::Errors::LimitExceededException)
```

It gets especially weird: When I uncomment one global_secondary_index from the user model, `rake aws_record:migrate` runs just fine (so it's not the db/table_config files). When I then Re-Insert the global_secondary_index in the user model and run `rake aws_record:migrate` again, all indexes are created correctly.

So the gem can't correctly handle if two global_secondary_indexes are defined in the same model and the migrations will be run after each other.

```
class User
  include Aws::Record

  string_attr :user_email
  string_attr :user_login

  global_secondary_index(:user_email_gsi,
                         hash_key: :user_email,
                         projection: { projection_type: 'ALL' })

  global_secondary_index(:user_login_gsi,
                         hash_key: :user_login,
                         projection: { projection_type: 'ALL' })

end
```

db/table_config/gsi_user_login.rb
```
require "aws-record"

module ModelTableConfig
  def self.config
    Aws::Record::TableConfig.define do |t|
      t.model_class User
      t.billing_mode "PAY_PER_REQUEST"
      t.global_secondary_index(:user_login_gsi)
    end
  end
end
```

db/table_config/user_email_gsi.rb

```
require "aws-record"

module ModelTableConfig
  def self.config
    Aws::Record::TableConfig.define do |t|
      t.model_class User
      t.billing_mode "PAY_PER_REQUEST"
      t.global_secondary_index(:user_email_gsi)
    end
  end
end
```

**Comment by mullermp** [comment]
Thanks for opening an issue. The error you encountered is a service side error - it looks like you are modifying the same table at the same time. I actually think you only need one migration here. `t.global_secondary_index` appends to a hash before execution. Try just a single migration:

```
module ModelTableConfig
  def self.config
    Aws::Record::TableConfig.define do |t|
      t.model_class User
      t.billing_mode "PAY_PER_REQUEST"
      t.global_secondary_index(:user_email_gsi)
      t.global_secondary_index(:user_login_gsi) 
    end
  end
end
```

**Comment by thomaswitt** [comment]
That seems to work, thank you.

**Comment by thomaswitt** [comment]
Sorry, I have to reopen. I run into the same issue again:

```ruby
# db/table_config/gsis_user.rb.rb
require 'aws-record'

module ModelTableConfig
  def self.config
    Aws::Record::TableConfig.define do |t|
      t.model_class User
      t.billing_mode 'PAY_PER_REQUEST'
      t.global_secondary_index(:user_email_gsi)
      t.global_secondary_index(:telegram_username_gsi)
    end
  end
end
```

```ruby
class User < BaseModel
  include Aws::Record
  include ActiveModel::Validations
# […]
  global_secondary_index(:user_email_gsi,
                         hash_key: :user_email,
                         projection: { projection_type: 'ALL' })

  global_secondary_index(:telegram_username_gsi,
                         hash_key: :telegram_username,
                         projection: { projection_type: 'ALL' })

```

results with dynamodb local in

```
running db/table_config/gsis_user.rb.rb
rake aborted!
Error deleting table: Subscriber limit exceeded: Only 1 online index can be created or deleted simultaneously per table
```

**Comment by mullermp** [comment]
You mentioned this issue for dynamodb local. Does it work in dynamodb production?

**Comment by thomaswitt** [comment]
@mullermp Just tried it in production, it also breaks in production with the real dynamodb.

I have a own rake task in an own namespace, which does as first task `Rake::Task['dynamo_db:reset_db'].invoke`.  That's when it fails. Let me know if you need more info to help.

**Comment by mullermp** [comment]
Yeah, what's in that reset db task? I don't think that is anything we have defined in this gem.

**Comment by thomaswitt** [comment]
Oh, sorry, I oversaw that, my bad. In the end it calls Rake::Task['aws_record:migrate'].invoke. For reference, here's the code:

```ruby
namespace :dynamo_db do
  desc 'Reset Database'
  task reset_db: :environment do
    if Rails.env.production? && ENV['RESET_PROD_DB'].blank?
      raise 'When running in production, you need to set env RESET_PROD_DB'
    end
    begin
      db = Aws::DynamoDB::Client.new

      # Check if using DynamoDB Local or AWS DynamoDB
      if db.config.endpoint && db.config.endpoint.to_s.include?('localhost')
        puts 'Using DynamoDB Local'
      else
        puts 'Using AWS DynamoDB'
      end
      table_name = BaseModel.table_name
      puts "Deleting DynamoDB table: #{table_name}"
      db.delete_table(table_name: table_name) rescue nil
      puts 'Waiting for table deletion'
      db.wait_until(:table_not_exists, table_name: table_name)
      puts "Table #{table_name} successfully deleted."

      Rake::Task['aws_record:migrate'].invoke
    rescue Aws::DynamoDB::Errors::ServiceError => e
      raise "Error deleting table: #{e.message}"
    end
  end
end
```

**Comment by thomaswitt** [comment]
@mullermp Thanks for the feedback! While I understand the concern about potential overloading, I believe the reset_db task is appropriately designed :
	1.	The rescue nil is intentional because the delete operation isn’t always guaranteed (e.g., if the table doesn’t exist). However, I agree that being too broad could obscure legitimate issues, and I might refine this. I don't think that this is the cause of the problem, because i still do the wait_until, unless that's broken. Creating or updating the table is exactly what I want btw, so nothing bad about this.
	2.	The task’s steps (delete, wait, migrate) reflect my requirement to reset the state completely before applying changes. ActiveRecord features something similar with rake db:migrate:reset.

I’ll add debugging code like you suggested to track it down.

**Comment by mullermp** [comment]
Deletion and creation in the same task is fine. My point is that rescuing from the base service error is fairly broad - you probably want to handle cases where deletion failed, or creation failed. Somehow I think update_table is being called. From what I can find, that error you are getting is from update_table called by migrate! in the table config. I think we just need to track down what calls are made there with a logger/wire trace.

As far as waiting goes, if the table doesn't exist, it should rescue and return nil immediately for you:

```
[3] pry(Aws)> dynamodb.wait_until(:table_not_exists, table_name: 'asdf')
[Aws::DynamoDB::Client 400 0.318157 0 retries] describe_table(table_name:"asdf") Aws::DynamoDB::Errors::ResourceNotFoundException Requested resource not found: Table: asdf not found
=> nil
```

**Comment by thomaswitt** [comment]
@mullermp The problem is still a real. As soon as I create two indexes in the same model, it's dysfunctional and I can't create indexes. Please try it for yourself, here is the exact steps to recreate the problem:

# Create a new rails app

`rails new checkme --css=tailwind --skip-active-record --skip-action-mailbox && cd checkme`

# Add SDK To Gemfile

```
gem 'aws-sdk-rails'
gem 'aws-record-rails'
```

# Create an initializer

```
# config/initializer/aws.rb
aws_config = {
  log_level: Rails.env.production? ? :warn : :debug,
  region: Rails.application.credentials.dig(:aws, :region) || "eu-central-1",
  credentials: Aws::Credentials.new('test', 'test')
}

Aws.config.update(aws_config)
if Rails.env.development?
  DYNAMODB_ENDPOINT = "http://localhost:8000"
  Aws.config.update(dynamodb: { endpoint: DYNAMODB_ENDPOINT })
end
```

# Create a base model

```
# app/models/base_model.rb
require "aws-record"
require "active_model"

class BaseModel
  include ActiveModel::Model
  include ActiveModel::Validations
  include Aws::Record
  extend ActiveModel::Callbacks
  define_model_callbacks :save, :update

  set_table_name "checkme"
  string_attr :hk, hash_key: true
  string_attr :rk, range_key: true
  string_attr :gsi_filter                 # Multi Function Filter Key
  string_attr :gsi_filter_rk            # Multi Function Filter Value

  global_secondary_index(:filter_gsi,
                         hash_key: :gsi_filter,
                         range_key: :gsi_filter_rk,
                         projection: { projection_type: "ALL" })
end
```

# Create a simple user model

```
# app/models/user.rb
class User < BaseModel
  include Aws::Record
  include ActiveModel::Validations

  string_attr :user_email
  string_attr :telegram_username

  validates_presence_of :user_email

  global_secondary_index(:user_email_gsi,
                         hash_key: :user_email,
                         projection: { projection_type: "ALL" })

  # FIXME https://github.com/aws/aws-sdk-ruby-record/issues/143
  global_secondary_index(:telegram_username_gsi,
                         hash_key: :telegram_username,
                         projection: { projection_type: "ALL" })
end
```

# Create table configs for the models

```
# db/table_config/base_model_config.rb
require "aws-record"

module ModelTableConfig
  def self.config
    Aws::Record::TableConfig.define do |t|
      t.model_class BaseModel
      t.billing_mode "PAY_PER_REQUEST"
      t.global_secondary_index(:filter_gsi)
    end
  end
end
```

```
# db/table_config/gsis_user.rb
require 'aws-record'

module ModelTableConfig
  def self.config
    Aws::Record::TableConfig.define do |t|
      t.model_class User
      t.billing_mode 'PAY_PER_REQUEST'
      t.global_secondary_index(:user_email_gsi)
      # FIXME https://github.com/aws/aws-sdk-ruby-record/issues/143
      t.global_secondary_index(:telegram_username_gsi)
    end
  end
end
```

# Run the migration
(assuming we have dynamodb local running, but same problem also appears in production)

```
. $ rake aws_record:migrate
running db/table_config/base_model_config.rb.rb
running db/table_config/gsis_user.rb.rb
rake aborted!
Aws::DynamoDB::Errors::LimitExceededException: Subscriber limit exceeded: Only 1 online index can be created or deleted simultaneously per table (Aws::DynamoDB::Errors::LimitExceededException)

Tasks: TOP => aws_record:migrate
(See full trace by running task with --trace)
```

**Comment by mullermp** [comment]
Thanks for the reproduction steps. I'll try to recreate this on Monday.

**Comment by thomaswitt** [comment]
@mullermp have a nice weekend:)

**Comment by mullermp** [comment]
Ok, so I am able to reproduce this, but I think this is expected behavior. What was not clear in your previous snippets was that you were running two migrations on the same table again (specifically, your base model config). I believe this was discussed earlier but I may have not done a good job explaining it. Table configs are intended to be declarative for a single table only. I understand you are using a base model for reusing code for your models, and that part is fine. However both your base model and the user model have the same table. You should only need one table config per table. Your migration should be:

```
# note - name your table configs after your table since they are 1:1
# should probably be users instead of checkme.
# consider also single table design: https://aws.amazon.com/blogs/compute/creating-a-single-table-design-with-amazon-dynamodb/

# db/table_config/checkme.rb
require 'aws-record'

module ModelTableConfig
  def self.config
    Aws::Record::TableConfig.define do |t|
      t.model_class User
      t.billing_mode 'PAY_PER_REQUEST'
      t.global_secondary_index(:user_email_gsi)
      t.global_secondary_index(:filter_gsi)
      t.global_secondary_index(:telegram_username_gsi)
    end
  end
end
```

If you're looking to reuse configuration for each of your tables, similar to having your base model, you could add a utility method perhaps:

```
# db/base_table_config.rb
module BaseTableConfig
  def self.base_config(t)
    t.billing_mode "PAY_PER_REQUEST"
    t.global_secondary_index(:filter_gsi)
  end
end

# db/table_config/checkme.rb
require 'aws-record'
require_relative '../base_table_config'

module ModelTableConfig
  def self.config
    Aws::Record::TableConfig.define do |t|
      t.model_class User
      BaseTableConfig.base_config(t)
      t.global_secondary_index(:user_email_gsi)
      t.global_secondary_index(:telegram_username_gsi)
    end
  end
end
```

**Comment by thomaswitt** [comment]
@mullermp Thanks for taking the time. Unfortunately, this hasn't led to a success yet either, so any way I turn it, I still get the same result regarding the index.

Let me maybe explain the (I think fairly straightforward) setup to make sure we're on the same page:
- I use a single table dynamodb table only, STI
- I have a ActiveModel (the `base_model.rb`) which defines hash and range keys, some basic callbacks like setting `created_at`/by + `updated_at`/by plus some secondary indexes which are valid for all types of data (like an index on last_changed_at). The type of item is hardcoded in the hash key (something like `id1234|USER`). This way way I implement easily e.g. a find_by_id class which inherits to all subclasses (translating into build_query with `id1234|CLASS_NAME`).
- I have about 7-8 other classes (like `User`, `Tenant`, …) which are based on the base_model. Again, it's all STI so the base_model defines the table_name and all the data is using it. That should be standard AWS practice.

Regarding secondary indexes:
- The base_model defines basic secondaries like the GSI on updated_at (same hash key like `id1234|CLASS_NAME` and range key for updated_at) eg via:
```
  global_secondary_index(:updated_at_gsi,
                         hash_key: :hk,
                         range_key: :updated_at_epoch,
                         projection: { projection_type: 'ALL' })
```

- The models themselves define other indexes they might need for their specific data (like user_email for the User Model:
```
  global_secondary_index(:user_email_gsi,
                         hash_key: :user_email,
                         projection: { projection_type: 'ALL' })

```

Maybe I haven't understood the idea of the migrations correctly, but the documentation for `Aws::Record::TableConfig` leaves more questions open for me than it answeres. Let me maybe face my problems/questions.

I understand that `Aws::Record::TableConfig.define` is just there to support the `rake aws_record:migrate` task so it can create/modify/add missing config data to the dynamodb table itself. As I only use PAY_PER_USE, the only meaningful configuration I supply there is my global_secondary_index (otherwise there would be no reason to redefine the global_secondary_index again as it's already defined in the model).

I don't actually really understand why I have to define a model_class as it this doesn't make sense in the (AWS recommended) way to use STI, as all models are basically mapping to the same data in the same table, which means you can't have different capacity configs anyway. And the global_secondary_indexes are globally defined for the tables anyway, so a `self.build_query.on_index(:user_email_gsi)` command doesn't care from what model I call it.


So technically the config I would like to have in an ideal world would be:

require 'aws-record'

```
module ModelTableConfig
  def self.config
    Aws::Record::TableConfig.define do |t|
    t.model_class BaseModel # This is even superfluous IMHO, but anyway.
    t.billing_mode 'PAY_PER_REQUEST'
    t.global_secondary_index(:filter_gsi)
    t.global_secondary_index(:item_id_gsi)
    t.global_secondary_index(:updated_at_gsi)
    t.global_secondary_index(:user_email_gsi)
    t.global_secondary_index(:telegram_username_gsi)
    end
  end
end
```

But that one doesn't work as I get an error

`Aws::DynamoDB::Errors::ValidationException: The table does not have the specified index: user_email_gsi (Aws::DynamoDB::Errors::ValidationException)`

The config how it's documented in `https://docs.aws.amazon.com/sdk-for-ruby/aws-record/api/Aws/Record/TableConfig.html` does only make sense in my understanding if you maintain a table per class, which is against AWS STI recommended practices.

So either I understood everything totally wrong or the way Aws::Record::TableConfig.define is built doesn't really align to STI practices.

Please enlighten me, what is the shortest and most recommended way to get my simple requirements working:
- Single Table Deisgn
- Multiple Models, inheriting from the same base class
- Simple Migration which just a) creates the table with the correct billing_mode and b) creates the secondary indexes.

**Comment by thomaswitt** [comment]
@mullermp Hi Matt - just kindly checking in if you got any hint how the functionality is to be used with a STI model?

**Comment by mullermp** [comment]
Hey. My understanding is that you should only have one table config class per table, regardless of using STI or not. That is because the table configs are declarative, for a single table. When you are running multiple table configs against one table, DynamoDB throws that error you are seeing, because it's already modifying the table. If you really want to have multiple table configs for the same table, you'll probably have to run them manually and not through the rake task, with some sleeping or some "waiter" that checks status of the table. If you are using multiple tables, you can share logic using the module approach. You may have multiple models for a single table and use inheritance as you've already done. As far as designing your STI, I am probably not the best person to consult for that.

Perhaps @alextwoods can provide any input or guidance.

**Comment by alextwoods** [comment]
Yeah, you're right that the TableConfig just does not map well to STI - I believe it was added in the library well before STI became a common/recommended pattern and we haven't added better abstractions to account for it.

The way you have structured your `BaseModel` and `User`, ect models using the same table make sense to me - I think thats generally the correct way to do that.

As to the TableConfig though - it does really fall apart.  Its an area of this gem that I don't personally love - in my own projects, I've generally preferred using cloudwatch/cdk to manage the infrastructure....  Anyway, that being said, I'd potentially recommend creating a "migration" only model that represents the desired state of the table, but doesn't have domain behavior (ie, letting you define the name/primary/secondary keys/gsi and nothing else.  I know thats not ideal though.  Improving this libraries STI functionality has been on my general list for awhile, but the changes I'd want to do would definitely require a new major version.

**Comment by thomaswitt** [comment]
@alextwoods @mullermp thanks for the reply and the reinforcement of my doubts. It's not really built for the way DynamoDB is intended to be used.

I read in [issue 142](https://github.com/aws/aws-record-ruby/issues/142#issuecomment-2548981860) that your work on aws-record is deprioritized, which is really a pity. I would really love to urge you to reconsider your position as seeing Ruby on Rails (especially in its current renaissance) as a second-class-citizen which it seems to have become the last years.

Quick Backstory:
I was involved in the development of many Rails apps highly utilizing DynamoDB (+Elastic/OpenSearch), deployed via FarGate which is a really winning combination for highly scaling apps which pose nearly no maintenance. Those apps are still running gazillions of records and are super rock solid. DynamoDB is an amazing product and IMHO for many applications the better backend than MySQL+Co is.

Back in the days when DynamoDB started, we started out with really basic-handcoding of every DynamoDB interaction, effectively building half of aws-record.

Then Dynamoid (https://github.com/Dynamoid/dynamoid) came out, which is a great effort and offers a great developer experience (sorry to say, I think way better developer experience then aws-record(-rails)), but unfortunately the developer pushed it into a direction of emulating MySQL: Multi-Table, Pseudo-Association-Relations, etc. which effectively is a really bad design pattern and does not conform to the STI idea of DynamoDB.

But it has many features out of the box which aws-record(-rails) should have, for example easy finder methods (find, find_by_id, where, .all, etc.) out of the box, updated/created_at timestamps, easy table configuration + working migrations, a .create method, support OOTB for validation callbacks, easy integration of third party classes via custom types (like Money), etc. Just take a look at the README, it's better documented and has a better API. But still there's the downside with the wrong design pattern. Yes, it does some kind of STI, but it's not fish, not meat. But in the end, that's the libary which should have come from AWS.

So that's why I decided against using Dynamoid in my projects but rather rely on aws-record. But of course it's not reassuring to start building larger apps on a technical basis where "[We have not prioritized aws-record work right now](https://github.com/aws/aws-record-ruby/issues/142#issuecomment-2548981860)".

It's really a pity that your own integration of DynamoDB for Ruby+Rails doesn't support THE main architectural STI pattern of DynamoDB.

Fast Forward: I really wish you would promote the use of DynamoDB much more, involve in the Rails community and give the GEM a real push by providing a great developer experience.

My ideal wish list for aws-record(-rails) would be:
- First Class Rails support, including those developer-experience-features mentioned for Dynamoid
- Custom types to make up synthetic attributes (important when you have a hash key like PARENT#TYPE#ID and you want to create a method to easily change the ID - [can be done easily in Dynamoid](https://github.com/Dynamoid/dynamoid?tab=readme-ov-file#custom-types))
- Native Support for using ActiveStorage
- Integration and support for the searchkick (https://github.com/ankane/searchkick) gem to index the records written to Elastic/OpenSearch
- If you think maybe CDK would make more sense, why not use CDK to run migrations on tables for aws-record-rails. All better than the current state.

Ideally the aws-sdk-rails would also make a deployment to Fargate (including main app + workers) a breeze (even if that's maybe even another different story - but:).

At the moment, you have to work around a lot of shortcomings and problems of the gem(s) if you really want to seriously use it. And especially as DHH does a big push against effectively YOU AWS guys with Kamal (which means effectively losing businesses for you), maybe it'd be a great initiative to show how Rails applications natively built for AWS can actually thrive.

Just my 2 cents. Happy to give more input if required.

**Comment by thomaswitt** [comment]
@alextwoods @mullermp The migrate task is actually so bad when creating multiple indexes that it indeed makes dynamodb-local to produce errors (as described by me in https://repost.aws/questions/QUmCWHpMIqSJa3eg2ALj_jYA/dynamodb-local-bug-creating-tables-leads-to-no-such-column-indexkey-4-sqlite-errors). I don't know why it does that (I guess has something to do with timing) and I don't have the time to investigate the internals of dynamodb-local. In the end it leads to SQLite errors with Dynamodb Local. That makes the migrate method unusable.

FYI, for now I ended up writing my own rake task which bases on the correct STI pattern, uses a base class and creates the correct table configuration. I attached it for your reference here, hoping that something like that will end up in the Gem (as the table creation mechanism is really dysfunctional at the moment).

(BTW; the base_class.attributes.attributes is still really really weird.)

```ruby
# lib/tasks/dynamodb.rake

namespace :dynamodb do
  desc 'Create a single DynamoDB table for all BaseModel subclasses'
  task create_table: :environment do
    create_single_table
  end

  desc 'Delete Table'
  task delete_table: :environment do
    if Rails.env.production? && ENV['ALLOW_ON_PROD_DB'].blank?
      raise 'When running in production, you need to set env ALLOW_ON_PROD_DB'
    end
    begin
      db = Aws::DynamoDB::Client.new

      if db.config.endpoint && db.config.endpoint.to_s.include?('localhost')
        puts 'Detected DynamoDB Local'
      else
        puts 'Detected AWS DynamoDB'
      end

      table_name = BaseModel.table_name

      begin
        db.describe_table(table_name: table_name)
        table_exists = true
      rescue Aws::DynamoDB::Errors::ResourceNotFoundException
        table_exists = false
      end

      if table_exists
        puts "Deleting DynamoDB table: #{table_name}"
        db.delete_table(table_name: table_name)
        puts 'Waiting for table deletion'
        db.wait_until(:table_not_exists, table_name: table_name)
        puts "Table #{table_name} successfully deleted."
      else
        puts "Table #{table_name} does not exist. Skipping deletion."
      end
    rescue Aws::DynamoDB::Errors::ServiceError => e
      raise "Error deleting table: #{e.message}"
    end
  end

  desc 'Reset the single DynamoDB table by deleting then creating'
  task reset_table: :environment do
    Rake::Task['dynamodb:delete_table'].invoke
    Rake::Task['dynamodb:create_table'].invoke
  end

  ##
  # Creates the single DynamoDB table for a given base model class (default:
  # BaseModel). Only attributes that are used as HASH or RANGE keys in either
  # the table definition or any GSI should be included in attribute_definitions.
  #
  # @param base_class [Class] The base model class to gather submodels from.
  #
  # @return [void]
  def create_single_table(base_class = BaseModel)
    Rails.application.eager_load!

    models = ObjectSpace.each_object(Class).select do |c|
      # c <= base_class ensures the base_class itself is included
      c <= base_class &&
        c.respond_to?(:attributes) &&
        c.respond_to?(:global_secondary_indexes)
    end

    table_name = base_class.table_name
    # $stderr.puts "\n[DEBUG] Discovered base_class: #{base_class}, table_name: " \
    #              "#{table_name}"
    # $stderr.puts '[DEBUG] Models found (including base_class):'
    # models.each { |m| $stderr.puts "  - #{m}" }

    # 1) Collect all key attributes from the main table schema
    #    and from each GSI across all models.
    used_key_attr_names = Set.new

    base_keys = base_class.keys
    hash_key_attr = base_class.attributes.attributes[base_keys[:hash]]
    range_key_attr = base_class.attributes.attributes[base_keys[:range]]

    used_key_attr_names << hash_key_attr.database_name
    used_key_attr_names << range_key_attr.database_name

    # $stderr.puts "[DEBUG] Base hash_key: #{hash_key_attr.database_name}, " \
    #              "range_key: #{range_key_attr.database_name}"

    # Gather GSI key attributes for all classes, including base_class
    gsi_definitions = []
    models.each do |model|
      # Next line calls Aws::Record's internal method that returns GSI configs
      definitions = model.global_secondary_indexes_for_migration
      gsi_definitions.concat(definitions)

      # $stderr.puts "[DEBUG] Checking model #{model}: found GSIs => " \
      #              "#{definitions.map { |d| d[:index_name] }}"
      definitions.each do |gsi|
        gsi[:key_schema].each do |ks|
          used_key_attr_names << ks[:attribute_name]
        end
      end
    end

    # 2) Build the table key_schema from base_class’s hash/range.
    table_key_schema = [
      { attribute_name: hash_key_attr.database_name, key_type: 'HASH' },
      { attribute_name: range_key_attr.database_name, key_type: 'RANGE' },
    ]

    # 3) Build a unique map of GSI definitions by index name.
    gsi_by_name = {}
    gsi_definitions.each do |gsi|
      # Convert symbol index_name to string, merge to avoid duplicates
      name_str = gsi[:index_name].to_s
      gsi_by_name[name_str] = gsi.merge(index_name: name_str)
    end

    global_secondary_indexes = gsi_by_name.values.map do |gsi|
      {
        index_name: gsi[:index_name].to_s,
        key_schema: gsi[:key_schema],
        projection: gsi[:projection],
        # If you need throughput, add :provisioned_throughput here
      }
    end

    # 4) Gather only key attributes (S, N, B).
    #    Non-key attributes or M/L/BOOL must NOT appear in attribute_definitions.
    attribute_definitions_map = {}
    models.each do |model|
      model.attributes.attributes.each_value do |attr_def|
        db_name = attr_def.database_name
        db_type = attr_def.dynamodb_type

        if used_key_attr_names.include?(db_name) && %w[S N B].include?(db_type)
          attribute_definitions_map[db_name] = db_type
        end
      end
    end

    # For debugging: show the final used key attribute names
    # $stderr.puts '[DEBUG] Used key attribute names: ' \
    #              "#{used_key_attr_names.to_a.inspect}"

    all_attribute_defs = attribute_definitions_map.map do |name, type|
      { attribute_name: name, attribute_type: type }
    end

    # 5) Build create_table params and attempt creation.
    create_params = {
      table_name: table_name,
      billing_mode: 'PAY_PER_REQUEST',
      attribute_definitions: all_attribute_defs,
      key_schema: table_key_schema,
    }
    if global_secondary_indexes.any?
      create_params[:global_secondary_indexes] = global_secondary_indexes
    end

    # Print final attribute definitions and GSI for debugging
    # $stderr.puts '[DEBUG] Final attribute_definitions: ' \
    #              "#{create_params[:attribute_definitions].inspect}"
    # $stderr.puts '[DEBUG] Final global_secondary_indexes: ' \
    #              "#{create_params[:global_secondary_indexes].inspect}" if create_params[:global_secondary_indexes]

    dynamodb = Aws::DynamoDB::Client.new
    begin
      puts "Creating table '#{table_name}'..."
      dynamodb.create_table(create_params)
      dynamodb.wait_until(:table_exists, table_name: table_name)
      puts "Table '#{table_name}' created successfully!"
    rescue Aws::DynamoDB::Errors::ResourceInUseException
      puts "Table '#{table_name}' already exists. Skipping creation."
    end
  end
end
```
