### ISSUE TITLE
ValidationError could have a more helpful message

### ISSUE THREAD

**Issue by benternet** [aws/aws-sdk-ruby-record#24]
"Validation hook returned false!" leaves you wondering what caused the hook to return false. When using ActiveModel::Validations the details of what validations failed are available by errors.full_messages.

I wonder if we could optionally use the ActiveModel::Validations errors.full_messages, or create a hook that would allow a consumer to inject whatever text they wanted for the ValidationError message.

**Comment by awood45** [comment]
I agree on this as a concept, and I'm considering the PR.

One reason it was done this way is to be as agnostic as possible to the validation method you bring. As your PR notes, the ability to get the error message for `ActiveModel::Validations` isn't broken by the not-super-helpful exception, so I want to be cautious about depending on the behavior of outside libraries.

**Comment by benternet** [comment]
Got it, agreed. Just hoping to find a way that makes it easier for consumers to get consistent behavior more easily while not being so intrusive. I've pushed another version of this that I feel has better separation and maybe that's far enough?

If not we can leave it up to the consumers to implement, but I really think it'd be great if this library could have some built-in assistance.

**Comment by awood45** [comment]
I think it's a reasonable idea to be able to decorate the exception thrown from a validation error in `#save!`, but such a hook would have to avoid new dependencies. If you look at the [gemspec](https://github.com/awslabs/aws-sdk-ruby-record/blob/master/aws-record.gemspec), we currently only depend on the `aws-sdk-resources` gem, which in turn only depends on the standard library and the `jmespath` gem (which is small and maintained by us). I'd like to avoid adding new required gem dependencies if at all possible.

**Comment by benternet** [comment]
Ah I see...sorry I totally glanced over the gem group. Agree that we shouldn't add a new dependency here.

We can just require any consumers to implement an `_aws_record_validation_error_message` as they see fit.

**Comment by awood45** [comment]
Another possibility (we've been discussing on this side offline) could be to change how we do the validation hook, slightly. I would not want to have `@api private` methods be overridden, since technically they're not part of the backwards compatibility guarantee, but we would sort of be saying "wink, nod, go for it just this one time".

You'd have a `:validator` member of an `Aws::Record` class, which could be overridden and provides the validation and error message hooks, possibly other hooks as well. By default, there's a null validator that does nothing (return `true` to all `#valid?` calls, return "You're not supposed to be here." for error messages, something of that sort). Main issue there is that it increases the risk of collision with whatever validation library you bring (not sure I could even use `#valid?` for that member, because that makes it difficult to cleanly bring in `ActiveModel::Validations`.

Working on it.

**Comment by benternet** [comment]
So would this look something like:

```ruby
# our_project/lib/aws-record/validation/active_model_validation.rb

module Aws::Record::Validation::ActiveModelValidation
  def self.valid?(subject)
    subject.valid?
  end

  def self.error_message(subject)
    return if valid?(subject)
    "Validation failed: #{subject.errors.full_messages.join(', ')}"
  end
end
```

```ruby
# our_project/app/models/thingy.rb

class Thingy
  include Aws::Record
  include ActiveModel::Validations

  aws-record_validation Aws::Record::Validation::ActiveModelValidation

  ...
end
```

And if validation failed you would raise your `AWS::Record::Errors::ValidationError` with our `Aws::Record::Validation::ActiveModelValidation.error_message`?

I could get behind that. It's a little unfortunate that we'd have to define our own `our_project/lib/aws-record/validators/active_model_validator.rb`, as would everyone else, but I totally agree that it shouldn't be built in to aws-record and add new dependencies on `ActiveModel::Validations` there.

**Comment by benternet** [comment]
Hey Alex any update here? I'm happy to help where I can, just let me know!

**Comment by awood45** [comment]
Sorry, I've been pulled into other things lately and haven't had a chance to spec out a hook for this. It's still something I want to look at before GA.

**Comment by awood45** [comment]
I've closed the related PR, and I'm going to talk about our thoughts on this:

This library is designed as a persistence layer, with the existing validation hook into `#save` and the exception hook in `#save!` provided as a convenience.

As a best practice, the `#save` vs `#save!` behavior does step around this issue, and doesn't require making one validation library preferred over another, or even any custom behavior at all. For example, there are two ways to handle an invalid record:

```ruby
item = Model.new(hash_key: "hk")

# Handling an invalid record via #save
unless item.save
  reason = item.errors.full_messages.join(", ")
  # Handle this however you find appropriate.
end

# Handling an invalid record via exceptions.
begin
  item.save!
rescue Aws::Record::Errors::ValidationError => e
  # Handling the error & message.
end
```

It's generally discouraged, for various reasons (many related to performance) to use exceptions for control flow. I am designing a simple/optional hook to allow users to define a custom ValidationError message pattern, but I don't want to go much further than that to avoid complexity.

Are there any reasons I'm missing for using `ValidationError` exceptions over if/else flow?
