### ISSUE TITLE
No link to example app

### ISSUE THREAD

**Issue by pas256** [aws/aws-sdk-ruby-record#31]
The documentation is ok, but an example Ruby on Rails 5 app with migrations would be truly awesome.

I imagine such an example exists somewhere. How else did you test this? :)

Can you please add a link to it in the README.

**Comment by awood45** [comment]
I don't have an example app out, but I think that's a good documentation request.

**Comment by awood45** [comment]
One feature request I have in mind, but haven't had a lot of feedback on yet, is to create a small add-on to integrate with Rails generators. We don't have that yet (so migrations work differently, for e.g. in a Rakefile), but I'm happy to hear about pain points to build the right thing.

One thing to keep in mind is that DynamoDB tables don't require migrations unless you're creating the table, or adding secondary indexes. Non-key/index attributes can be added or removed at will.

**Comment by pas256** [comment]
Not even somewhere in awslabs?

What I love about this idea is (almost) doing away with migrations, but they are still required. Creating new tables, adding indexes.

I think https://github.com/Dynamoid/Dynamoid looked at some of these things.

Bonus points if the Rails app uses the DynamoDB emulator for dev and test :)

**Comment by awood45** [comment]
Yup, I hear that. I'll take it as a request for a sample app that does these things.

Depending on feedback over time, we can also add additional features to the migration helper (nothing stopping us from wrapping it with something tightly integrated with Rails).

**Comment by pas256** [comment]
Hey, I am finally getting around to playing with this and cannot get it to work. In the spirit of helping others, I have begun the example application. You can find it here:

https://github.com/pas256/aws-record-example-ruby

Something must have changed recently though because the example migration from the current documentation doesn't work with the AWS SDK:

```
$ rails ddb:migrate
Creating/Migrating DynamoDB tables...
rails aborted!
ArgumentError: no such member :  provisioned_throughput
/Users/pas256/.rvm/gems/ruby-2.3.0@aws-record-example-ruby/gems/aws-sdk-core-2.6.5/lib/seahorse/model/shapes.rb:212:in `member'
```

**Comment by awood45** [comment]
That is interesting, I took a look at your code and nothing stood out as wrong right away. I've got a similar piece of code running on production (non-Rails, but that shouldn't matter) projects without issues.

Since this would imply a fairly serious SDK bug, can you try reinstalling the aws-sdk gem? I'm wondering if somehow your API model files are corrupted.

**Comment by pas256** [comment]
This was completely fresh - done just a few hours ago, and adding the `aws-record` gem is what added `aws-sdk-core`. Versions are:

    aws-record 1.0.1
    aws-sdk-core 2.6.5

which is latest

**Comment by awood45** [comment]
I'm able to pull down your code and get the same error. Taking a look at it.

**Comment by awood45** [comment]
Okay, this is strange. I got your example to work, but I didn't change anything. I think your file may actually have an encoding problem, because when I deleted it and typed it in from scratch, it worked. (Emacs was yelling at me to add a UTF-8 encoding header to the file, which drew my suspicion.)

I can give you a pull request if you would like.

**Comment by pas256** [comment]
yes please.

If that's the case, then the issue goes back to the encoding on the blog post :-(

**Comment by awood45** [comment]
That's entirely possible, and I'll take a look at that with the blog platform team. Sorry about that!

**Comment by awood45** [comment]
I've sent you a PR with the encoding fixed. It works for me locally. Thanks for making this, please do let me know if you run in to any other issues or if feature requests come to mind as you work.
