### ISSUE TITLE
#empty? on ItemCollection always returns false

### ISSUE THREAD

**Issue by pye2k** [aws/aws-sdk-ruby-record#35]
On a table that has no matches, I ran `#empty?` and `#count` expecting to get `true` and `0`, respectively. The following is what I got from `rails console`.

```
irb(main):018:0> Resource.scan({filter_expression: "resource_id = ABC"}).empty?
[Aws::DynamoDB::Client 200 0.103658 0 retries] scan(filter_expression:"resource_id = ABC",table_name:"resources_test")

=> false
irb(main):019:0> Resource.scan({filter_expression: "resource_id = ABC"}).count
[Aws::DynamoDB::Client 200 0.067079 0 retries] scan(filter_expression:"resource_id = ABC",table_name:"resources_test")

=> 0
```

If I'm reading this correctly, the [test cases for #empty](https://github.com/aws/aws-sdk-ruby-record/blob/master/spec/aws-record/record/item_collection_spec.rb) also expect false (always).

Am I missing something here?

**Comment by awood45** [comment]
No, I don't think you're missing anything here, I think I missed something in the code review. If we're supporting `#empty?`, it should work for an empty response.

**Comment by pye2k** [comment]
I dug more into this... I have a fix, I'll send a pull request in a few mins!

**Comment by awood45** [comment]
Thanks, I have another test for you to check (I was about to write this also), I'll move that to the PR.

**Comment by awood45** [comment]
Thanks for the PR, it will go out with the next release.

**Comment by awood45** [comment]
I've pushed version 1.0.1 with this bug fixed.
