### ISSUE TITLE
Is query limit supported?

### ISSUE THREAD

**Issue by imackinn** [aws/aws-sdk-ruby-record#39]
I'm having some trouble limiting the results of a query on an index. I keep trying to impose a limit of 50 but I still get all the results that match the index query. Is Limit supported? or am I missing something?

```
Post.query(
        index_name: "blog_id-posted_time-index",
        key_condition_expression: "#H = :h AND #R < :r",
        limit: 50,
        expression_attribute_names: {
            "#H" => "blog_id",
            "#R" => "posted_time"
        },
        expression_attribute_values: {
            ":h" => blog_uuid,
            ":r" => timestamp
        }
    )
```

Where `Post` includes `Aws::Record`.

**Comment by awood45** [comment]
The `:limit` parameter is respected, but the `#query` method is returning an enumerable object which will automatically paginate - in essence, it is respecting your limit _per request_, but making additional requests.

**Comment by awood45** [comment]
The collection type is [documented here](http://docs.aws.amazon.com/awssdkrubyrecord/api/Aws/Record/ItemCollection.html).

One option is to also limit the number of items you take from the response - depends on your use case. The class doesn't currently expose the underlying response object.

**Comment by imackinn** [comment]
@awood45 gotcha; thanks for such a prompt reply; will construct statue in your honour when I rule the world.
