### ISSUE TITLE
DybamoDB local

### ISSUE THREAD

**Issue by fcastellanos** [aws/aws-sdk-ruby-record#42]
Is there a way to access the dynamodb local with this gem?

**Comment by awood45** [comment]
It would be similar to how you would access it with the Ruby SDK in general. You should be able to create a client with a custom endpoint, and make that your table client. For example:

```ruby
class Model
  include Aws::Record
  string_attr :uuid, hash_key: true
end

local_client = Aws::DynamoDB::Client.new(region: "local") # If you use a different port than 8000, set a custom endpoint too.
Model.configure_client(client: local_client)
```

**Comment by awood45** [comment]
Closing as this should be all you need. Feel free to reopen if this doesn't work for you.

**Comment by fcastellanos** [comment]
Thanks!

**Comment by fcastellanos** [comment]
hey @awood45 that did not work, it's still creating the table in AWS, this is what I have in the initializer at the moment just for test:

```
local_client = Aws::DynamoDB::Client.new(region: 'local')

MyModel.configure_client(client: local_client)

migration = Aws::Record::TableMigration.new(MyModel)

migration.create!(
  provisioned_throughput: {
    read_capacity_units: 5,
    write_capacity_units: 2
  }
)
migration.wait_until_available
```

**Comment by awood45** [comment]
Apologies, there's a second part for table migrations. Try this:

```ruby
local_client = Aws::DynamoDB::Client.new(region: 'local')

MyModel.configure_client(client: local_client)

migration = Aws::Record::TableMigration.new(MyModel, client: local_client)

migration.create!(
  provisioned_throughput: {
    read_capacity_units: 5,
    write_capacity_units: 2
  }
)
migration.wait_until_available
```

**Comment by TylerSustare** [comment]
I know this was from ~5 years ago but it's worth mentioning that #101 really helps out by stating that you need to use `endpoint: 'http://localhost:8000'` as well as the region due to `https/http` missmatch with DDB local.
