### ISSUE TITLE
Projecting Specific Columns in find

### ISSUE THREAD

**Issue by prasathsarath** [aws/aws-sdk-ruby-record#46]
As of now when doing `Cars.find(id: 1, manufacturer_id: 1)` it gives whole row, but what if I have 
structure like this,
`{
 id: 1,
manufacturer_id: 1, 
style: {
color: red,
rim_present: true
}
}`, so now I want only the style portion of  the car not the whole record. The only possible way now is `query` but I know the primary key(id, manufacturer_id) values
Is it possible like `Cars.find(id:1, manufacturer_id: 1, projection_expression: 'style')` or something on the lines of this?

**Comment by awood45** [comment]
With your exact example, it is not possible to reduce the record further, as the key values are always included. Do you have other fields beyond those that you wished to exclude?

You can use a projection expression to choose which non-key fields to use, but that's currently not available in #find (adding that is an open feature request).

**Comment by prasathsarath** [comment]
Thanks for the response @awood45. I believe you are asking for the fields other than `style` column, if so, yes I have some set of columns which are of type **Map**. 
Consider for the below car row:
`{
  id: 1, manufacturer_id: 1, style: { color: red, rim_present: true },
  extra_features: {
    core: {
      engine: 'BMW B58 Turbocharged DOHC'
    },
    rim: {
      color: 'black'
    }
  }
}`

Sometimes I need only Extra Feature's engine name, so I may query like below:
`CallQueues.find(id: 1, manufacturer_id: 2, project_expression: 'extra_features.core.engine')` for projecting a key's value in Map.

**Comment by awood45** [comment]
This is an interesting use case because I suspect it could break the way map dirty tracking works currently. You'll be able to do this with the `#find_with_opts` PR I am submitting, but you would risk clobbering the rest of your map if you make alterations and save them. How to handle this case cleanly would take further investigation.
