### ISSUE TITLE
Rspec testing/mocks

### ISSUE THREAD

**Issue by tenyo** [aws/aws-sdk-ruby-record#56]
Hi, I just started using this gem in a Rack (Sinatra) project and I love it! I'm starting to write some rspec tests and was wondering what's the best way to stub the calls to Aws::Record.

For example, my model looks like this:
```
    class Resource
      include Aws::Record
      configure_client client: ddb_client

      string_attr   :id, hash_key: true
      string_attr   :type
      string_attr   :status
      map_attr      :data
    end
```

In my code I have something like this:
```
Resource.find(id: uuid)
```

What's the best way to stub that call (and possibly others, e.g. `scan` or `query`)? 
I guess it could do this but I'm not sure how to set up the Record object:
```
expect(Resource).to receive(:find).and_return(record)
```

Any examples would be appreciated!

**Comment by IbottaBaier** [comment]
If didn't already implement a bulk-set method, you could make a factory with said functionality:

```
  def build(attributes = {})
   record = Record.new
    attributes.each do |name, value|
      record.send("#{name}=", value)
    end
    record
  end

  record = Record.build(id: 1, type: 'foo', status: 'bar', data: 'lorem ipsum')
```

As for stubbing vs. mocking the `find` call, a snippet from `dirty_tracking_spec.rb` specs shows:
```
expect(klass).to receive(:find).with({ mykey: reloaded_instance.mykey }).
        and_return(reloaded_instance)
```

**Comment by tenyo** [comment]
Thanks for the response! I looked into this some more and I don't think the bulk-set method will work in this case as I actually need to return an ItemCollection object (since I'm running `collect` on it in my code). I could possibly make it work, but I'm not sure how useful that would be for my testing as it's only one case. Ideally, I would just stub the responses from `Aws::DynamoDB::Client` but I can't make that work.

Here's what I have so far:
```
context 'when single resource' do
  let(:stub_client) { Aws::DynamoDB::Client.new(stub_responses: true) }
  subject { get '/v1/api/resources' }

  it 'returns list of ids' do
    stub_client.stub_responses(
      :get_item,
      item: { 'id' => '012345', 'type' => 'test', 'data' => 'test' }
    )
    expect(Aws::DynamoDB::Client).to receive(:new).and_return(stub_client)
    expect(subject.status).to eq(200)
    expect(subject.body).to eq(['012345'])
  end
end
```

However, when I run rspec I get `ERROR -- <Aws::DynamoDB::Errors::UnrecognizedClientException: The security token included in the request is invalid.>` I assume that's because the call to `Aws::DynamoDB::Client` never got intercepted and it's trying to use empty credentials.

My `Resource` class (listed in the previous post) configures the DynamoDB client via this `ddb_client` method:
```
def ddb_client
  Aws::DynamoDB::Client.new(
    region: Config.auth['dynamodb']['region'],
    access_key_id: Config.auth['dynamodb']['accesskey'],
    secret_access_key: Config.auth['dynamodb']['secret']
  )
end
```

I would expect rspec to intercept that call via `expect(Aws::DynamoDB::Client).to receive(:new).and_return(stub_client)` but it doesn't seem to happen.

I looked at the specs for aws-sdk-ruby-record but they all create their own classes (allowing them to call configure_client), e.g.
```
let(:klass) do
    Class.new do
      include(Aws::Record)
      configure_client(client: stub_client)
    ...
```

In my case I'm trying to use my already defined `Resource` class and I don't understand how to override the client that it uses for the test.

**Comment by IbottaBaier** [comment]
I ran into the same issue; you need to override your `configure_client` with the stubbed client.

I wrote this wrapper:
```
class Resource
   ....
   def self.with_client(client)
      current_client = dynamodb_client
      TestRecord.configure_client(client: client)
      yield
      TestRecord.configure_client(client: current_client)
   end
end
```

Then in your test you can:
```
stub_client.stub_responses(
  :get_item,
  item: { 'id' => '012345', 'type' => 'test', 'data' => 'test' }
)
Resource.with_client(stub_client) do
    expect(subject.status).to eq(200)
    expect(subject.body).to eq(['012345'])
end
```

**Comment by tenyo** [comment]
Awesome! This is exactly what I needed, thank you!

**Comment by awood45** [comment]
The above example is a working way to stub the DynamoDB behavior, similar to what the gem's own test libraries do. I am open to ideas on how to expose useful test helper behavior.

If you want to assume a successful response, the first example of stubbing a new record works fine. You could make something like the following from your above example:

```ruby
class Resource
  include Aws::Record
  configure_client client: ddb_client
  string_attr   :id, hash_key: true
  string_attr   :type
  string_attr   :status
  map_attr      :data
end

# In your test
record = Resource.new(id: "stub_value", type: "stub_type", status: "stub_status", data: { value: 2 })
record.clean! # Clears dirty tracking, which may be important for simulating next behavior steps
expect(Resource).to receive(:find).and_return(record)
```

**Comment by IbottaBaier** [comment]
The difference being whether you prefer mocking vs. stubbing.

**Comment by awood45** [comment]
Agreed, but it's another alternative. I'm inclined to think from this discussion that creating mock responses (or stubbing the client) is reasonable enough to not need a full-featured stubbing integration (perhaps a blog post or dev guide). I'm open to differing opinions on that.

**Comment by IbottaBaier** [comment]
I feel like the existing stub response/data functionality provided by `Aws::DynamoDB::Client` is sufficient. However, a blog post pointing people towards `configure_client(stub_client)` for testing with stubs might be nice.

**Comment by tenyo** [comment]
I think a blog post about how to set up mocking and stubbing for Aws::Record would be perfect. Adding a `self.with_client` is key for getting the stubbing to work. As for mocking responses, I would be interested in how I could return an ItemCollection object (in the case of `query` and `scan`).

**Comment by IbottaBaier** [comment]
Alternatively you can just always have a stubbed client for test: 
```
class Resource
  configure_client(client: Aws::DynamoDB::Client.new(stub_responses: Rails.env.test?))
end
```

Technically the client is used across multiple tests, but it's not a problem as long as you re-stub responses each time (would not work well with mocking, however).

**Comment by IbottaBaier** [comment]
You can also use the RSpec `around` clause to automatically handle the wrapper for each test.
```
around(:each) do
  with_client(stub_client) do
    example.call()
  end
end
```
