### ISSUE TITLE
TableConfig is not in the docs

### ISSUE THREAD

**Issue by omnibs** [aws/aws-sdk-ruby-record#65]
Is it manually updated?

![image](https://cloud.githubusercontent.com/assets/1060410/25531136/1dde4438-2bff-11e7-97db-f9e4e43ff698.png)

**Comment by awood45** [comment]
Thanks for the report - looks like an issue with our release process. The docs should be present in a few minutes, I'll leave open until I can confirm. Thanks for the report!

**Comment by awood45** [comment]
Docs updated. [TableConfig docs are here](http://docs.aws.amazon.com/awssdkrubyrecord/api/Aws/Record/TableConfig.html). Thanks for the report!
