### ISSUE TITLE
Datetime format stored and queried

### ISSUE THREAD

**Issue by jakephot** [aws/aws-sdk-ruby-record#68]
When storing a UTC `datetime` object with `date_time_marshaler.rb`, the stored value is in "2017-01-01T09:05:00+00:00" format, not "2017-01-01T09:05:00Z". 
This makes it necessary to manually format `datetime` with the following code before using it in query, like `date_time_marshaler.rb` does internally. 

    date_string = DateTime.parse(Time.at(date.to_i).utc.to_s).iso8601 #=> "2017-01-01T09:05:00+00:00"
    date_string = date.iso8601 #=> "2017-01-01T09:05:00Z"

I feel it will be helpful if we can save datetime in "2017-01-01T09:05:00Z" format, or if we can pass a `datetime` object in `expression_attribute_values`.

**Comment by awood45** [comment]
Currently, that is possible using your own marshaler. If you consider the [default marshaler](https://github.com/aws/aws-sdk-ruby-record/blob/master/lib/aws-record/record/marshalers/date_time_marshaler.rb#L64), you could write your own module that follows the same format, and pass it in to the `:formatter` option. We have an example of this in our [unit tests](https://github.com/aws/aws-sdk-ruby-record/blob/master/spec/aws-record/record/marshalers/date_time_marshaler_spec.rb#L90).

I am open to taking a pull request for alternative datetime marshalers as well to add in to the class, which would make it as simple as setting an option when defining your datetime attribute.

**Comment by IbottaBaier** [comment]
I just convert everything to seconds (or milliseconds) as an integer. The `integer_attr` is great for this since you can say:
```
record.date = Time.now
record.date #=> Time.now.to_i
```

**Comment by awood45** [comment]
This is probably a good time for me to plug the fact that you can create custom marshalers. If you want to store as an epoch integer, but surface as a date object, you absolutely can write marshalers that do this, and directly use the `#attr` method to define your attribute using custom marshalers.

**Comment by awood45** [comment]
We're not going to change this marshaller, but the query story is going to be getting better with serializer helpers in the query/scan builder feature I'm working on now.
