### ISSUE TITLE
TableConfig Local Secondary Index

### ISSUE THREAD

**Issue by natesalisbury** [aws/aws-sdk-ruby-record#73]
Are there plans to support declaring local secondary indexes in a `TableConfig`?

**Comment by awood45** [comment]
There are not. Local secondary indexes can only be created at table creation time, and it's considered a best practice as I understand it to move towards using global secondary indexes in new tables. However, a TableConfig for a table with existing local secondary indexes should not cause any problems.

**Comment by awood45** [comment]
I'll take a note of the request though, and if it's something broadly desired, I can take a pull request for it.

**Comment by natesalisbury** [comment]
I didn't realize moving to GSIs is a best practice, thanks for letting me know. I just figured if the partition keys were going to be the same you would want to use a local secondary index. I'll just go with a GSI. Thanks!

**Comment by awood45** [comment]
Sounds good - I'll leave this open for a bit to see if there are other requests for this before closing.
