### ISSUE TITLE
datetime_attr with millisecond resolution?

### ISSUE THREAD

**Issue by steveclarkin** [aws/aws-sdk-ruby-record#76]
I was wondering if something could point me to or provide an example on how to use a custom formatter for datetime_attr? I would like to store datetime in DynamoDB to millisecond resolution. ie. "2017-09-10T06:32:53.484Z"

I understand that this should still work as a range key and BETWEEN should work when querying for rows between two datetimes of millisecond resolution?

**Comment by awood45** [comment]
The [test file](https://github.com/aws/aws-sdk-ruby-record/blob/master/spec/aws-record/record/marshalers/date_time_marshaler_spec.rb) for date-time marshaling shows an example of how to do this. That example just calls a different formatter method on the DateTime object, but there's no reason you can't put any logic you would like in there.

**Comment by IbottaBaier** [comment]
I use an `integer_attr` to store the value then use a setter override I wrote to convert the value (note this also requires a monkey patch to `Time` for the `#millis` function).
```ruby
    # Forces attributes designated by provided keys as millis.
    #
    # @example
    #   class My Record
    #     include Ibotta::Dynamo::Record
    #
    #     integer_attr :millis_timestamp
    #     force_millis :millis_timestamp
    #   end
    #
    #   record = MyRecord.new
    #   record.millis_timestamp = Time.now
    #   record.millis_timestamp #=> Time.now.millis
    #
    # @param args [Symbol] attribute symbols to be converted to millis
    def force_millis(*args)
      args.each do |key|
        define_method("#{key}=") do |value|
          if value.is_a?(Numeric) || !value.respond_to?(:millis)
            set_attribute(key, value)
          else
            set_attribute(key, value&.millis)
          end
        end
      end
    end
```

**Comment by metaskills** [comment]
Came here for another reason because I think `time_attr` should have defaulted to seconds and use the `(N)` type vs `(S)` as it does now If for performance reasons this is true, I'm gonna try something like this in my code. NOTE: Not tested, just pseudo code.

```ruby
module Aws
  module Record
    module Marshalers
      class TimeIMarshaler

        def initialize(opts = {})
        end

        def type_cast(raw_value)
          case raw_value
          when nil
            nil
          when ::Time
            raw_value.to_i
          else
            raw_value.to_i
          end
        end

        def serialize(raw_value)
          case raw_value
          when nil
            nil
          when ::Time
            raw_value
          when ::Integer # timestamp
            ::Time.zone.at(raw_value)
          else
            msg = "expected a Integer value or nil, got #{raw_value.class}"
            raise ArgumentError, msg
          end
        end

      end
    end
  end
end

Aws::Record::Attributes.module_eval do

  def timei_attr(name, opts = {})
    opts[:dynamodb_type] = "N"
    attr(name, Marshalers::TimeIMarshaler.new(opts), opts)
  end

end
```

**Comment by awood45** [comment]
Would `:epoch_time_attr` work for your use case? Seems very similar.

**Comment by metaskills** [comment]
Uh... yes 😅 - I missed that.

**Comment by awood45** [comment]
Definitely a fair shout that I should have done the defaults as epoch values, but this was well requested and added a few releases back. Should have closed this back then too, so I will now :)
