### ISSUE TITLE
Why become nil?

### ISSUE THREAD

**Issue by ken-sayama** [aws/aws-sdk-ruby-record#90]
Thank you for making a wonderful Gem!

During development, I use local DynamoDB.
Data could be saved to DynamoDB, but scan will be nil for some reason.

```
require 'aws-record'

class Transaction
  include Aws::Record
  set_table_name "hoges"

  string_attr :id, hash_key: true
  boolean_attr :processed

  local_client = Aws::DynamoDB::Client.new(region: "localhost", endpoint: 'http://localhost:8000',)
  self.configure_client(client: local_client)
end

scan = Transaction.scan(
  expression_attribute_names: {"#p": "processed"},
  expression_attribute_values: {":val": {"BOOL": false}},
  filter_expression: "#p = :val",
)

puts scan # nil
```

**Comment by ken-sayama** [comment]
There are some data in it.

**Comment by awood45** [comment]
A `puts` call is going to return nil. What happens when you run:

```ruby
puts scan.first.to_h
```

**Comment by ken-sayama** [comment]
The result will be returned like this

```
{}
```

**Comment by ken-sayama** [comment]
In this way all the data could be acquired.

```
require 'aws-record'

class Transaction
  include Aws::Record
  set_table_name "hoges"

  string_attr :id, hash_key: true
  boolean_attr :processed

  local_client = Aws::DynamoDB::Client.new(region: "localhost", endpoint: 'http://localhost:8000',)
  self.configure_client(client: local_client)
end

scan = Transaction.scan

scan.each do |r|
  puts r.id
end
```

**Comment by awood45** [comment]
Sounds like you were able to sort things out for your table. The important thing to keep in mind is that the ItemCollection object returned by the aws-record scan call is a lazy enumerator, it won't have values pre-included. This can be important, say, if you have 1,000,000,000 items in your table, you wouldn't want eager scanning of your full table. Providing the lazy enumerator allows you to fetch only the paged data you need.

Feel free to add any questions or re-open if you still have a problem.
